- master.xml
Change-Id: I6ad5340f871ab201608b34433b6a9627f902ac86
> master: add new SDK tool to manifest: mantle!

- master.xml
Change-Id: Ifdf2c250942b0e663b020f2e0b207e486bffb461
> master: add rocket to manifest

- master.xml
Change-Id: I38ea18701b9fbed08e210a8866dbbe479e9531e8
> master: add etcd-starter

- master.xml
Change-Id: I83787bfbf9a879f583cf2f2610e5a181fa54e642
> master: add systemd repo to SDK

- master.xml
Change-Id: I1d45871021d82b40ba15afc4045cfa2b088d81db
> master: add mayday repo

- build-640.xml
- master.xml
Change-Id: I719e6dba390c0cbf71a68a53864c79b1673d8659
> master: remove etcd-starter

- master.xml
Change-Id: Ie258a496d09947a9fc622ace4af3ce598c74e526
> master: add appc/spec repo

- master.xml
Change-Id: I55662e9f269738e6fff609ff078a260459f428a5
> master: rename vboot_reference to seismograph

- master.xml
Change-Id: I305a6ce91245954fa44743611d37bf2c2cf8ce83
> master: add Ignition

- master.xml
Change-Id: Ia4f7253cc324c57612eec94458c669c7d0c226fb
> master: add coreos-metadata

- build-835.xml
Change-Id: I26d4049b58632e17384c83c320890c5408783a17
> build-835: include fix for and CVE-2016-0777 and CVE-2016-0728

- build-899.xml
Change-Id: I96aa2b07c4a30ddad1a2f838114d86f97e49e21b
> build-899: include fix for CVE-2016-0728

- build-935.xml
- master.xml
Change-Id: I0b285c75f117b42ff256c562fb955c435c2e1d74
> add appc/acbuild @ v0.2.2

- build-1010.xml
Change-Id: If4a59b5811eb4e708ed0f8b3c75cf9ae6625d195
> build-1010: follow new branch in coreos/init project

- build-1068.xml
Change-Id: Idddb00ee1266e663089ce531d7f978be77a5de28
> build-1068: branch coreos-overlay

- build-1068.xml
- release.xml
Change-Id: I23f84f888b39bbf6663c6320998c60b9b4a64379
> build-1068: branch scripts, split branch and release manifests

- build-1081.xml
Change-Id: I07d4fad6d648148247cb697bbf5b6b3e0828c695
> build-1081: branch coreos-overlay and portage-stable

- build-1010.xml
Change-Id: Ifcc27879215b2be0e3f1ab2da461c8f5f510bf9b
> build-1010: branch scripts

- build-1122.xml
- default.xml
Change-Id: I56bff71da0b8f7f86b4b0855fe88766f4e7e7093
> build-1122: branch portage-stable and coreos-overlay

- build-1153.xml
- default.xml
Change-Id: Icb6396cf85c5e884603449f35c610dd2e136902c
> build-1153: release v1153.1.0

- build-1153.xml
- default.xml
> Revert "build-1153: release v1153.1.0"

- build-1153.xml
- default.xml
Change-Id: I54fbda1280f3f9a380b64ac0a9550dd261fb1cf2
> build-1153: start branch

- build-1153.xml
Change-Id: Ie782d56c54ba4508844a37c273c9cf1448a507d9
> build-1153: branch portage-stable

- build-1164.xml
- default.xml
- release.xml
Change-Id: Ie65c0c92aa00abf5e67cab13474250064d79f432
> build-1164: branch coreos-overlay

- build-1185.xml
- default.xml
Change-Id: I8fd296514fdd0fb3ebd5c3b03c96cff059d4b648
> build-1185: branch update_engine

- build-1192.xml
- default.xml
Change-Id: I2fc85a437e54e84bb258a4fdd26706c21135aca9
> build-1192: branch scripts

- build-1192.xml
Change-Id: I9cac24c8b6d999d5ab7e0dd175006b295fb385af
> build-1192: branch coreos-overlay

- build-1220.xml
- default.xml
Change-Id: Ib393d6fa7f8bbdc95407b436b7ff0168896fb9f4
> build-1220: branch coreos-overlay

- build-1220.xml
- default.xml
> Revert "build-1220: branch coreos-overlay"

- build-1235.xml
- default.xml
Change-Id: Iaab9758d8c26ed978d80389425e90df606ff16d8
> build-1235: branch coreos-overlay

- build-1248.xml
- default.xml
Change-Id: I1bd0938c37ef4763bd047c131d97cc95e2eff840
> build-1248: branch coreos-overlay

- build-1325.xml
- default.xml
Change-Id: I8d910f42f19a229a72932dfde834e0ac88c356dd
> build-1325: branch portage, overlay, and scripts

- build-1367.xml
Change-Id: I9d8768bb54eacf15db16ceec4426e8263bb9e006
> build-1367: branch overlays + scripts

- default.xml
Accidentally missed this in the previous change
Change-Id: I389ffe3ffd6f7c09ace46eae90a55206bb655d8c
> build-1367: update default symlink

- build-1381.xml
- default.xml
Prepare this version for beta in two weeks (or any alpha minor releases before then).
> Preemptively branch projects in the build-1381 branch

- master.xml
Include a torcx clone in everyone's SDK for `cros_workon` etc.
> master: add torcx

- build-1353.xml
This doesn't really do anything, but there is a branch now, so why not.
> build-1353: branch init for stable

- build-1409.xml
Same as #138, since this beta becomes stable.
> build-1409: branch init for beta

- master.xml
Drop some repositories which appear to be unused.  I've verified that a full Jenkins build with fresh workspaces succeeds.
Please feel free to suggest additions/subtractions to the repository list.
> master: Drop unused repositories

- master.xml
Part of coreos/coreos-overlay#2718.
> master: Drop Docker

- master.xml
https://github.com/coreos/coreos-overlay/pull/2868
cc @ajeddeloh
> master: Drop crostestutils

- master.xml
Depends on https://github.com/coreos/coreos-overlay/pull/3025.
> master: Drop fleet

- _remotes.xml
- master.xml
Change-Id: Id30d59ba9865fb1c121ca58be3b9f8f10418fc68
> master: remove unused stuff

- master.xml
Part of https://github.com/coreos/coreos-overlay/pull/3624.
> master: rename coreos-metadata to afterburn
